basePath: /api
definitions:
  api.LoginRes:
    properties:
      token:
        description: token
        type: string
    type: object
  dto.LoginRequest:
    properties:
      passWord:
        description: 密码
        type: string
      userName:
        description: 用户名
        type: string
    required:
    - passWord
    - userName
    type: object
  dto.RoleRes:
    properties:
      desc:
        description: 描述
        type: string
      id:
        type: integer
      roleName:
        description: 角色名
        type: string
      value:
        description: 角色code
        type: string
    type: object
  dto.UserRes:
    properties:
      avatr:
        description: 头像
        type: string
      desc:
        description: 描述
        type: string
      homePath:
        description: 主页路径
        type: string
      id:
        type: integer
      realName:
        description: 真实姓名
        type: string
      roles:
        description: 角色
        items:
          $ref: '#/definitions/dto.RoleRes'
        type: array
      userName:
        description: 登录名
        type: string
    type: object
  response.Result:
    properties:
      code:
        description: 业务code 0 代表成功
        type: string
      cost:
        type: string
      data:
        description: 成功返回的数据
      message:
        description: 提示信息
        type: string
    type: object
info:
  contact:
    email: me@razeen.me
    name: Razeen
    url: https://razeen.me
  description: This is a sample server celler server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: https://razeen.me
  title: Swagger Example API
  version: "1.0"
paths:
  /login:
    post:
      consumes:
      - application/json
      operationId: Login
      parameters:
      - description: 登陆参数
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/dto.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 成功返回
          schema:
            allOf:
            - $ref: '#/definitions/response.Result'
            - properties:
                data:
                  $ref: '#/definitions/api.LoginRes'
              type: object
        "400":
          description: 参数错误
          schema:
            allOf:
            - $ref: '#/definitions/response.Result'
            - properties:
                message:
                  type: string
              type: object
      summary: 用户名密码登陆
      tags:
      - Login
  /loginout:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/response.Result'
      summary: 退出登录
      tags:
      - Login
  /ping:
    get:
      consumes:
      - multipart/form-data
      description: 向你说Hello
      operationId: Ping
      parameters:
      - description: 人名
        in: query
        name: who
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: 测试SayHello
      tags:
      - Ping
  /userInfo:
    get:
      consumes:
      - application/json
      parameters:
      - description: Authorization
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 成功返回
          schema:
            allOf:
            - $ref: '#/definitions/response.Result'
            - properties:
                data:
                  $ref: '#/definitions/dto.UserRes'
              type: object
      summary: 查询登录用户信息
      tags:
      - User
swagger: "2.0"
tags:
- description: 登录
  name: Login
- description: 用户
  name: User
